### ISSUE TITLE
can't display errorMessage while trying to register with same details

### ISSUE THREAD

**Issue by vamsee9** [jgbijlsma/mern-auth-template-tutorial#1]
I am following your tutorials and everything is working fine and displaying status code but errorMessage cannot display in chrome console  please check the following screenshot and please help me as soon as possible.

![Screenshot 2021-05-13 111920](https://user-images.githubusercontent.com/46225107/118083992-870f4000-b3dd-11eb-9278-4347e104e9fa.png)

**Comment by anogray** [comment]
![image](https://user-images.githubusercontent.com/57917151/119999285-33ad0c80-bfef-11eb-82ae-2f7a89b544de.png)

The axios err has the Error Messages but you need to extract the message of error

![image](https://user-images.githubusercontent.com/57917151/119999401-5808e900-bfef-11eb-9529-fa4fac37cf73.png)

**Comment by vamsee9** [comment]
@anogray 

Thanks I have already find it out and done fixed.
